# Generated by Django 4.2.2 on 2023-06-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default='email', max_length=40),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=40),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_usuario',
            field=models.CharField(default='Nombre Usuario', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrimeraApp.perfil'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='PrimeraApp.perfil'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='PrimeraApp.perfil'),
        ),
    ]
